### ISSUE TITLE
homu.io is down

### ISSUE THREAD

**Issue by oblitum** [barosl/homu#129]
The site has been down for a long time.

**Comment by stefanpenner** [comment]
friendly ping

**Comment by nokaa** [comment]
In the meantime, an old version of homu.io can be viewed [here](https://archive.is/ctWrq).

**Comment by barosl** [comment]
Urgh, I'm very, very sorry.

homu.io consists of two parts, one is a Python daemon (this repository) and the other is a website backend written in Rust. I thought homu.io was alive because I only checked [the queue page](http://homu.io/q/barosl/homu), which is provided by the Python daemon. (And [the contribution activity](https://github.com/homu) shown in the profile page was also OK, because the Python daemon is also responsible for answering r+ requests.) So I thought this issue was just a temporal one. But the real problem was with the website backend, which blocked repository/reviewer addition/deletion.

I'm again terribly sorry for being careless. Now the problem is resolved.

I really have to unify those two daemons into a single one...

**Comment by oblitum** [comment]
Nice, it's up again!

**Comment by rwjblue** [comment]
Thanks @barosl!

**Comment by stefanpenner** [comment]
@barosl thank you kindly sir. I appreciate that you are able to continue to maintain this.

**Comment by glyn** [comment]
@barosl homu.io appears to be down again.
