### ISSUE TITLE
Merge commit message should also contain PR title

### ISSUE THREAD

**Issue by barosl** [barosl/homu#65]
Currently, a merge commit message only contains the body of the pull request. It would be useful to include the title too.

However, it seems that bors' merge commit messages also contain only the bodies, so I'm not entirely sure. Was that behavior intentional? If it was, we'd better reconsider this.

**Comment by pnkfelix** [comment]
I don't think the original bors behavior was intentional.

I am *strongly* in favor of making this change.

I have been trying to always make copies of my titles in my descriptions, and even editing *other peoples* descriptions to paste their title in the description as well, just to work around this problem with bors/homu.
