### ISSUE TITLE
Saving State

### ISSUE THREAD

**Issue by alexcrichton** [barosl/homu#8]
Long term request: If homu is restarted while a build is running, the current build must be retried, but it would be nice for the restarted homu to re-learn the state of the previous instance, not requiring the build to be retried.

**Comment by alexcrichton** [comment]
ping @barosl, I think this may be the only remaining blocker for letting homu loose on rust-lang/rust

We almost always have quite a long queue of approved PRs, and having to re-retry all PRs which are in the queue because of `@bors: retry` may not work on in the long run (we're bound to forget some). Would there be an easy way to at least track the retry-able state between runs of homu?

**Comment by barosl** [comment]
@alexcrichton The PRs that should be `retry`ed after the bot restarts are the ones that are in `PENDING` state. As there should be only one `PENDING` PR at a time, it would not be too difficult to determine which PR should be `retry`ed.

The only exception to this is the `try` feature, which triggers a new build simultaneously. In this case, there can be more than one `PENDING` PRs, which should all be `retry`ed.

**Comment by alexcrichton** [comment]
Ah ok, I may have just misread something then. So let's say I have this situation:

* PR A fails on buildbot
* I write `@bors: retry` on PR A, but it's now at the end of a long queue
* homu is restarted

Does homu still have PR A in the queue after that?

**Comment by barosl** [comment]
@alexcrichton Ah, now I see the problem. In that scenario, PR A becomes `APPROVED` after you write `retry`, not `PENDING`. And the `APPROVED` state is not recorded in GitHub. So after the restart, you will see PR A as `FAILED` again.

This happens because:

1. Homu recognizes the `retry` command only from the Webhooks API. It is to prohibit the existing `retry` comments (that was already parsed before a restart) from taking effect after a restart.
2. However, the `APPROVED` state is not recorded in GitHub, as there is no such thing in GitHub.

I believe this is definitely a case of needing a local state management.

**Comment by barosl** [comment]
I had thought the methods for saving an external state.

1. SQLite: Save a state using a local SQLite database. This method is also used by Buildbot. The possible downside I guess is that it can be bothersome to maintain a local file.
2. Blobs API: It can sound crazy, but GitHub does support a [`Blobs` API](https://developer.github.com/v3/git/blobs/). We can save arbitrary data to a repository using a SHA-1 key. The upside of this is that we don't need to save anything on local. The downside is that it will decrease the overall performance, especially on the boot-up process when Homu retrieves information of all the PRs.

**Comment by alexcrichton** [comment]
For now I think we should go with a sqlite database, but we could look into expanding to GitHub later for certain!
